In [1]:
import numpy as np

In [10]:
matrix = np.random.randint(0, 10, size=(4, 3, 5))
print("原始矩阵:")
print(matrix)
print()

print(matrix.shape)

transposed_matrix = np.transpose(matrix, (0, 2, 1))
print(transposed_matrix.shape)

mask = np.array([[True, False, True, False, True],
                [False, True, False, True, False],
                [True, False, True, False, True],
                [False, True, False, True, False]])

print(mask.shape)


原始矩阵:
[[[1 1 5 1 0]
  [2 6 1 4 0]
  [6 3 0 0 6]]

 [[2 4 3 6 4]
  [3 4 5 2 9]
  [0 9 2 1 6]]

 [[4 2 4 5 0]
  [2 6 3 4 4]
  [1 2 8 4 4]]

 [[5 1 7 9 6]
  [1 9 9 4 5]
  [9 2 0 6 5]]]

(4, 3, 5)
(4, 5, 3)
(4, 5)


In [11]:
transposed_matrix[mask,:] = 0

In [13]:
matrix_new = np.transpose(transposed_matrix, (0, 2, 1))
print(matrix_new)

[[[0 1 0 1 0]
  [0 6 0 4 0]
  [0 3 0 0 0]]

 [[2 0 3 0 4]
  [3 0 5 0 9]
  [0 0 2 0 6]]

 [[0 2 0 5 0]
  [0 6 0 4 0]
  [0 2 0 4 0]]

 [[5 0 7 0 6]
  [1 0 9 0 5]
  [9 0 0 0 5]]]


In [2]:
matrix = np.array([[True, False, True],
                   [False, True, False],
                   [True, True, False]])

# 统计 True 的个数
count_true = np.count_nonzero(matrix)

In [3]:
print("True 的个数:", count_true)

True 的个数: 5


In [9]:
MaxAmplMatrix = np.array([[10, 20, 30],
                 [100,200, 300],
                 [400,500,900]])
ShadowTHValue = 400
level2_1_mask = MaxAmplMatrix < ShadowTHValue
print(level2_1_mask)

[[ True  True  True]
 [ True  True  True]
 [False False False]]


In [12]:
SD_counter = np.count_nonzero(level2_1_mask)
print(SD_counter)

6


In [1]:
a = "C:/Users/AlexChen/Desktop/HSI_DP_local/RefBoard/3.csv"

In [8]:
print(a[-6:])

/3.csv


In [15]:
class test:
    a = 0
    def __init__(self):
        a = 1
        func(a)
    def func(self,a):
        self.a = 2

test()
print(test.a)

0


In [18]:
a = 1
b = 2
a = b
print(a)
b = 3
print(a)

2
2


In [19]:
import threading

# 定义一个函数作为线程的执行体
def thread_function():
    # 线程的具体操作逻辑
    print("Thread is running.")

# 创建一个线程对象
thread = threading.Thread(target=thread_function)

# 启动线程
thread.start()

# 主线程继续执行其他操作
print("Main thread continues.")

# 等待线程结束
thread.join()

# 线程结束后执行的操作
print("Thread finished.")

Thread is running.Main thread continues.

Thread finished.
