In [10]:
import numpy as np

matrix = np.random.randint(0, 10, size=(4, 3, 5))
print("原始矩阵:")
print(matrix)
print()

print(matrix.shape)

transposed_matrix = np.transpose(matrix, (0, 2, 1))
print(transposed_matrix.shape)

mask = np.array([[True, False, True, False, True],
                [False, True, False, True, False],
                [True, False, True, False, True],
                [False, True, False, True, False]])

print(mask.shape)


原始矩阵:
[[[1 1 5 1 0]
  [2 6 1 4 0]
  [6 3 0 0 6]]

 [[2 4 3 6 4]
  [3 4 5 2 9]
  [0 9 2 1 6]]

 [[4 2 4 5 0]
  [2 6 3 4 4]
  [1 2 8 4 4]]

 [[5 1 7 9 6]
  [1 9 9 4 5]
  [9 2 0 6 5]]]

(4, 3, 5)
(4, 5, 3)
(4, 5)


In [11]:
transposed_matrix[mask,:] = 0

In [13]:
matrix_new = np.transpose(transposed_matrix, (0, 2, 1))
print(matrix_new)

[[[0 1 0 1 0]
  [0 6 0 4 0]
  [0 3 0 0 0]]

 [[2 0 3 0 4]
  [3 0 5 0 9]
  [0 0 2 0 6]]

 [[0 2 0 5 0]
  [0 6 0 4 0]
  [0 2 0 4 0]]

 [[5 0 7 0 6]
  [1 0 9 0 5]
  [9 0 0 0 5]]]
